@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
## valid uuid = 50cf148b-d8c9-48c9-94e3-91551f3ed62b

### Create Category
POST http://{{host}}/categories
Content-Type: {{contentType}}

{
  "name": "Drama",
  "description": "some description"
}

###  List categories
GET http://{{host}}/categories
Content-Type: {{contentType}}

### Get category
GET  http://{{host}}/categories/5a9a64ed-8c92-4189-9662-e787621c3aef
Content-Type: {{contentType}}

### Update category
PATCH  http://{{host}}/categories/8180d203-77eb-47f9-a3b6-2d9375cc6ed2
Content-Type: {{contentType}}

{
  "name": "Drama",
  "description": "some description"
}

### Delete category
DELETE  http://{{host}}/categories/8180d203-77eb-47f9-a3b6-2d9375cc6ed2
