version: '3'

services: 
  app: 
    build: .
    command: ./.docker/start.sh
    container_name: micro-videos-app
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    depends_on:
      - db
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
  
  db:
    image: mysql:8.0.30-debian
    container_name: micro-videos-db
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33006:3306
    volumes:
       - ./mysql-config:/etc/mysql/conf.d
    tmpfs:
      - /var/lib/mysql
